---
title: "Get Glottolog data for language family, macroarea, "
author: "Steven Moran"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output:
  github_document:
  pandoc_args: --webtex
---
  
```{r, echo=FALSE, include=FALSE}
library(dplyr)
```

# Glottolog languoids data

```{r}
# Glottolog languoids
# https://cdstar.shh.mpg.de/bitstreams/EAEA0-E7DE-FA06-8817-0/glottolog_languoid.csv.zip
glottolog.languoid.csv <- read.csv('glottolog_languoid.csv/languoid.csv', stringsAsFactors = FALSE)
```

```{r}
# Have a look at the Glottolog languoid csv data
glimpse(glottolog.languoid.csv)
```

```{r}
# How many levels?
table(glottolog.languoid.csv$level)
```

```{r}
# Unique language family ids. This includes all dialects, empty family_id strings, etc.
sort(table(glottolog.languoid.csv$family_id, exclude = FALSE), decreasing = TRUE)
```


# Language families and their Glottocodes for language
```{r}
# Just family ids and Glottocodes
families.glottocodes <- glottolog.languoid.csv %>% filter(level == "language") %>% filter(family_id != "")
glimpse(families.glottocodes)
```


# Language families and their Glottocodes counts
```{r}
# Family ids and Glottocode counts
families.counts <- families.glottocodes %>% group_by(family_id) %>% summarize(count=n()) %>% arrange(desc(count))
dim(families.counts)
```

# Isolates 
```{r}
# Get language isolates
isolates <- glottolog.languoid.csv %>% filter(family_id == "") %>% filter(parent_id == "") %>% filter(level=="language")
glimpse(isolates) # 188
```

# Marcoareas
```{r}
# All languages per macroarea (and their counts) -- note names not unique
# languages.dialects.geo <- read.csv(url("https://cdstar.shh.mpg.de/bitstreams/EAEA0-E7DE-FA06-8817-0/languages_and_dialects_geo.csv"))
languages.dialects.geo <- read.csv("languages_and_dialects_geo.csv", stringsAsFactors = FALSE)
glimpse(languages.dialects.geo)
```

```{r}
# Get Glottolog macroareas and language counts
languages.geo <- languages.dialects.geo %>% filter(level=="language") %>% filter(macroarea!="") %>% group_by(glottocode)
languages.geo
```
```{r}
table(languages.geo$macroarea)
```

```{r}
languages.geo.counts <- languages.geo %>% group_by(macroarea) %>% summarise(counts=n())
languages.geo.counts
```

```{r}
save(families.glottocodes, families.counts, isolates, languages.geo, file='glottolog-families-isolates.Rdata')
# write.csv(families.glottocodes, families.counts, isolates, languages.geo, file='glottolog-families-isolates.csv')
```
